services:
  eureka-server:
    image: eureka-server:1.0-SNAPSHOT
    container_name: eureka-server
    ports:
      - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Tehran
    networks:
      - spring
  banking-service:
    image: banking-service:1.0-SNAPSHOT
    container_name: banking-service
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Tehran
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge