server:
  port: 8081

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          main-client:
            registration:
              client-id: main-client
              client-secret: "{bcrypt}$2a$10$CC11Bw0Hcw03qiJlgwN/I.M/XevGIEOQ5Z4r/f.Nrq7R3ZpxYUb26"
              client-name: main-client
              client-authentication-methods:
                - client_secret_post
              authorization-grant-types:
                - client_credentials
              scopes:
                - test.test
            token:
              access-token-time-to-live: 3600s

logging:
  level:
    org.springframework.security: trace
