server:
  port: 8081

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          main-client:
            registration:
              client-id: main-client
              client-secret: "{noop}secret"
              client-name: main-client
              client-authentication-methods:
                - client_secret_basic
                - client_secret_post
              authorization-grant-types:
                - client_credentials
                - authorization_code
                - refresh_token
              redirect-uris:
                - http://127.0.0.1:8080/authorized
              scopes:
                - openid
                - profile
                - message.read